FROM mcr.microsoft.com/dotnet/sdk:8.0

WORKDIR /app

# Copy csproj and restore dependencies
COPY ["EHRBS-backend.csproj", "./"]
RUN dotnet restore

EXPOSE 80

ENTRYPOINT ["dotnet", "watch", "run", "--urls", "http://+:80"]